source 'https://github.com/brightcove/BrightcoveSpecs.git'

platform :ios, '8.0'
use_frameworks!

target 'example' do
    pod 'Brightcove-Player-Core'
  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'ReactNativeNavigation', :path => '../node_modules/react-native-navigation'

end
